[project]
name = "nrf-ble-host"
version = "0.1.0"
description = "BLE host tools for nRF devices"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["bleak>=0.22", "pydantic>=2", "rich>=13"]

[project.scripts]
nrf-ble = "nrf_ble.cli:main"

[tool.pytest.ini_options]
addopts = "-q"
